dist/debian: use scylla-boost163 on Debian9
We get following compile error with distribution provided boost-1.62:

/usr/include/boost/icl/type_traits/type_to_string.hpp:56:12: error: partial specialization of 'struct boost::icl::type_to_string<Unary<Type> >' after instantiation of 'struct boost::icl::type_to_string<std::__cxx11::basic_string<char> >' [-fpermissive]
     struct type_to_string<Unary<Type> >
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/icl/type_traits/type_to_string.hpp:72:12: error: partial specialization of 'struct boost::icl::type_to_string<Binary<Type1, Type2> >' after instantiation of 'struct boost::icl::type_to_string<std::__cxx11::basic_string<char> >' [-fpermissive]
     struct type_to_string<Binary<Type1, Type2> >
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To fix the build error, we neeed to switch to scylla-boost163.

Fixes #3223