configure.py: add -Wno-sign-compare to prevent compilation error on antlr3 header
We get follwoing compile error on Debian/Ubuntu:

/opt/scylladb/include/antlr3cyclicdfa.inl:170:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if  ( c == ImplTraits::CommonTokenType::TOKEN_EOF && m_eof[s] >= 0)

To fix the build error, we need to add -Wno-sign-compare on cflags.

Fixes #3222