configure.py: add -Wno-uninitialized to prevent compilation error on Boost.Intrusive
We get following compile error on Debian/Ubuntu:

/opt/scylladb/include/boost/intrusive/pointer_plus_bits.hpp:76:48: error: '*((void*)& __tmp +136)' is used uninitialized in this function [-Werror=uninitialized]
       n = pointer(uintptr_t(p) | (uintptr_t(n) & Mask));
                                  ~~~~~~~~~~~~~~^~~~~~~

To fix the build error, we need to add -Wno-uninitialized on cflags.

Fixes #3090